version: '3'

services:
  mongodb:
    image: mongo:4.4
    container_name: yapi-mongo
    volumes:
      - ./data/mongo:/data/db
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=yapi
    networks:
      - yapi-network

  yapi:
    image: jayfong/yapi:latest
    container_name: yapi
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      - YAPI_ADMIN_ACCOUNT=admin@kysion.com
      - YAPI_ADMIN_PASSWORD=ky-admin123
      - YAPI_CLOSE_REGISTER=true
      - YAPI_DB_SERVERNAME=mongodb
      - YAPI_DB_PORT=27017
      - YAPI_DB_DATABASE=yapi
      - YAPI_MAIL_ENABLE=false
      - YAPI_LDAP_LOGIN_ENABLE=false
    restart: always
    networks:
      - yapi-network

networks:
  yapi-network:
    driver: bridge 